sophgo/bootloader-riscv

.github/workflows/build.yml
scripts/envsetup.sh
zsbl/plat/sg2042/boot.c

1. add mango-milkv-pioneer.dtb to support milkV Pioneer EVB
2. modify scripts to support new name: mango-sophgo-x8evb.dtb

adjust mango dtb file name

---

zsbl/plat/sg2042/Makefile
zsbl/plat/sg2042/boot.c
zsbl/plat/sg2042/include/ini.h
zsbl/plat/sg2042/ini.c

The conf.ini contains board configuration information. The convention is that the conf.ini must start at byte 0 with a section called sophgo-config, without any comments. In addition, the current conf.ini contains the [devicetree] section, which has two keys, namely name and addr.
The conf.ini is saved in SPI Flash1 and will be added to EEPROM in the future.

zsbl: plat: sg2042: detect board type dynamically

---

zsbl/plat/sg2042/boot.c

When the conf.ini does not contain dtb info, still enter the original branch to get dtb name.

Fix: support case that dtb name is not in conf.ini

---

scripts/envsetup.sh

- remove the step of copying compiled files about U-Boot and GRUB2

scripts: fix the error log when building rv image

---

scripts/envsetup.sh

An error is reported when executing the following shell
Shell: source scripts/envsetup.sh
Error: scripts/envsetup.sh:96: = not found

fix bug of scripts/envsetup.sh

---

scripts/envsetup.sh

1.Expand the tolerable time of nvme io transmission and management timeout to 600s.
2.Expand contiguous memory allocator from 16M to 512M 
3.Expand swiotlb from 64M to 128M
The purpose is to fix ext4fs error bug.

scripts:Add parameters in fedora kernel command line

---

.github/workflows/build.yml
scripts/envsetup.sh
scripts/github_env.sh

- Refine the build_rv_grub ().
- Add the EDKII and GRUB2 binaries into the Ubuntu and Fedora image to support the UEFI+GRUB2 boot flow on SG2042.

scripts: Support the UEFI+GRUB2 boot flow

---

scripts/envsetup.sh

Supplement the necessary parameters to avoid the ext4fs error occurring.

scripts: Add params to grub.cfg in Fedora image

---

scripts/envsetup.sh

Remove "quiet" to show the boot log for debugging; "splash" causes the BMC RTC to work badly because "splash" will use the framebuffer by the BMC's BAR to load and store the pixel.

scripts: remove "quiet splash" from grub.cfg

---

scripts/envsetup.sh

Building the riscv-gnu-toolchain is not parallelized, leading to relatively slow build times. This commit uses the `make -j$(nproc)` convention to parallelize building GCC and friends, as is done elsewhere in the script. For my machine, build time improves from 87 minutes to 15.
Resolves: #84

scripts: Parallelize building GNU toolchain

---

scripts/envsetup.sh

1. CPU mode should run: CHIP=sg2044 source bootloader-riscv/script/envsetup.sh
2. AI mode should run: CHIP=bm1690 source bootloadr-riscv/script/envsetup.sh

riscv: sophgo: modify CHIP option for sg2044 and bm1690

---

scripts/envsetup.sh

1. mkdir use -p parameters to avoid mkdir return error when the directory is already exists.
2. umount use directory parameters to avoid umount dev can only remove one dev node, if there are multi dev mount to this dir, only umount one dev will not remove all dev node on this dir.

sg2044: fix compile warning when build_rv_ubuntu_image.

---

scripts/envsetup.sh

let $CHIP=bm1690, run build_rv_zsbl to compile zsbl.bin for rp, run build_rv_tp_zsbl to compile tp_zsbl.bin for tp.

bm1690: add build_rv_tp_zsbl to compile zsbl for tpu-scalar.

---

scripts/envsetup.sh

rp_Image and riscv64_Image is the same file. rp_Image is used for PCIe mode, riscv64_Image is used for first stage linux for rp in Soc mode.

bm1690: set rp_Image name also to riscv64_Image for Soc mode.

---

scripts/envsetup.sh

To use || for OR test, [[ ]] should be used instead of [].
This fixes below error:
scripts/envsetup.sh: line 1784: [: missing `]'
scripts/envsetup.sh: line 1784: mango: command not found

Fix incorrect use of [ || ]

---

scripts/envsetup.sh

If we install linux-image-6.5.5.deb in Ubuntu24.04, then run apt update, will cause flash-kernel error. So delete this file that we don't use to avoid this error.

script: fix flash-kernel error after install image.

---

ramdisk/rootfs_202405/etc/init.d/S10mdev
ramdisk/rootfs_202405/etc/mdev.conf
scripts/envsetup.sh

1. modify compile rootfs way to found no ap deamen problem.
2. rootfs use mdev to update /dev

script: terminate compile rootfs when no ap deamen.

---

scripts/envsetup.sh

Image.gz is one of the dependencies of bindeb-pkg, compilation may fail with multiple threads

script:bugfix:: remove Image.gz from rp bindeb-pkg make command

---

scripts/gen_sg2042_img.sh
service/sg2042-pisces/powergood/power_good.sh
service/sg2042-pisces/powergood/powergood.service

The second linux kernel may be stuck for an infinite time due to failure to mount rootfs normally, users couldn't reconnect to this system after executing reboot because of the problem. 
within five minutes after power-on, the BMC will detect the power good signal of successfully entry into linux system. If no signal is detected, BMC will notify the CPLD to restart.

Add and enable powergood signal service in SG2042 multi-chips server

---

scripts/gen_sg2042_img.sh

When CHIP_NUM=single, [ -e /etc/systemd/system/powergood.service] return 1, this will be considered as a compilation problem and exit directly because the building environment has executed 'set -e'.

scripts:gen_sg2042_image:avoid returning non-zero value on exit

---

scripts/gen_sg2042_img.sh

In function build_rv_euler_image, there is only a `popd` without `pushd`, which caused "directory stack empty" error

sctipt:sg2042::remove single `popd`

---

scripts/envsetup.sh

In the daily-build system, the checkout operation synchronizes remote changes stored in the refs/remotes/* space. However, if we also perform a checkout during the local build process, the local changes in the refs/heads/* space can lead to synchronization issues, including potential version rollbacks.

scripts: remove checkout op when building EDK II

---

scripts/envsetup.sh

Now we use PCIe zsbl config for BM1690 in sg2260-pld branch, so keep this cmd until BM1690 switch to zsbl master branch.

scripts: revert build_rv_pcie_zsbl for BM1690.

---

scripts/envsetup.sh
scripts/gen_sg2044_img.sh

- Add DTB generation to build_rv_ubuntu/euler_kernel.
- Only copy the DTB file corresponding to the specified $CHIP into the firmware directory.
- For SG2044, Remove the LinuxBoot binaries when build_rv_*_image process; remove the LinuxBoot build process when build_rv_firmware.

scripts: refine build process

---

scripts/envsetup.sh

Different versions of the Linux kernel have varying build paths.

scripts: fix build_rv_euler_kernel bug

---

scripts/envsetup.sh
scripts/gen_sg2044_img.sh

- Moved the DTB copy earlier to avoid issues with kernel Makefile version or rpmbuild tool version inconsistencies.
- FSBL source code is not publicly available; the daily build system updates the SG2044 binary at a fixed link and will automatically download it if missing locally.

scripts: refine mango and sg2044 build scripts

---

packages/openeuler-24.03/kernel/README.md
packages/openeuler-24.03/kernel/cpupower.config
packages/openeuler-24.03/kernel/cpupower.service
packages/openeuler-24.03/kernel/kernel.spec

This spec helps creating rpm packages which built from linux kernel. These packages are
bpftool
bpftool-debuginfo
kernel
kernel-debuginfo
kernel-debugsource
kernel-devel
kernel-headers
kernel-source
kernel-tools
kernel-tools-debuginfo
kernel-tools-devel
perf
perf-debuginfo
python3-perf
python3-perf-debuginfo

SG2044: Add kernel.spec of openEuler 24.03

---

scripts/envsetup.sh
scripts/pack_firmware_bin/gen_firmware_xml.c
scripts/pack_firmware_bin/pack_firmware_bin.c

Modified the matching method for version info in the format of x.x.x_yyyy-mm-dd. And optimized the code format.

Scripts: fix some bugs

---

scripts/envsetup.sh

Update riscv-gnu-toolchain checkout point from
2023.11.08 to 2025.06.13.

toolchain: upgrade riscv-gcc from 13.2 to 15.1

---

scripts/ap_tp_kernel.patch
scripts/envsetup.sh

AP/TP will not use this configuration.

riscv:config: disable ZONE_DMA32 and SWIOTLB for ap/tp.
