sophgo/bootloader-riscv

- scripts/envsetup.sh
1. Change the default Linux kernel version to 6.1.X
2. Upgrade openSBI to v1.2 from v0.8
> Change the version of the Linux kernel & OpenSBI

- scripts/envsetup.sh
add perf source package & build script in sd.img
> scripts: add build_rv_perf_tool

- scripts/envsetup.sh
-- fix bug: copy grub.efi to faulty dir
> boot-loader:scripts: modify envsetup.sh

- scripts/envsetup.sh
scripts/envsetup.sh fix string compare
> fix shell string equal

- scripts/envsetup.sh
Cancel the startup loading of the switchtec module
> scripts: Add sg2042-blacklist.conf file in rootfs

- scripts/envsetup.sh
- Remove the build_rv_grub_cfg_tmpl ().
- Refine the build_rv_grub ().
- Add the build_rv_edk2 () and clean_rv_edk2 ().
- Add the edk2 and u-boot binaries info into the partition table of SPI Flash.
> scripts: Add the EDKII compilation script

- scripts/envsetup.sh
Set the $WORKSPACE variable in build_rv_edk2() to override the default $WORKSPACE value by jenkins.
> scripts: Fix compilation automatically bug

- scripts/envsetup.sh
Remove nvme timeout setting from kernel command line.
> Remove nvme timeout setting from kernel command line.

- scripts/envsetup.sh
ubuntu img 24.04 have been discarded.
> sg2044: update ubuntu img to 24.04.1

- ramdisk/overlay/ap/etc/init.d/S60apveth
- ramdisk/overlay/rp/etc/init.d/S60rpveth
add S60rpveth and S60apveth to set veth ip is 192.192.chipid.2
> add shell to set ap and rp veth

- ramdisk/rootfs_202405/etc/fstab
Support debugfs auto mount for user modify clk.
> rootfs: auto mount debugfs for ramdisk.

- scripts/envsetup.sh
run build_rv_pcie_zsbl for bm1690 pcie rp boot.
> script: add cmd for build bm1690 pcie mode zsbl.

- LICENSE
add GPL v2 license declaration
> add license declaration

- scripts/envsetup.sh
use cmd:
build_rv_kernel rp pkg
to package deb for rp ramdisk.
> script: build linux-header for rp ramdisk insmod ko.

- ramdisk/overlay/rp/etc/init.d/S60rpenv
- scripts/envsetup.sh
> update rp ramdisk package

- scripts/envsetup.sh
User can use build_rv_ramdisk ap/rp/tp/mini to build cpio, but CI should use build_rv_ramdisk_ci to check file.
> script: add build_rv_ramdisk_ci for Jenkins.

- ramdisk/overlay/rp/etc/init.d/S30rpdaemond
> revise rp scripts error

- ramdisk/overlay/rp/etc/init.d/S30rpdaemond
it seems that the order of modins matters,so i adjust it to the right position
> adjust modins order

- scripts/gen_sg2044_img.sh
zsbl will load conf.ini by name.
> scripts: rename config.ini to conf.ini.

- ramdisk/overlay/ap/etc/init.d/S30apdaemond
- ramdisk/rootfs_202405/etc/init.d/S50sshd
fixed ssh service can't start issue in the ap/rp/tp ramdisk
> changed ssh key right for ssh service

- scripts/envsetup.sh
- scripts/make_pack_tool.sh
- scripts/make_xml.c
- scripts/pack/.gitignore
- scripts/pack/README.md
- scripts/pack/ezxml/GNUmakefile
- scripts/pack/ezxml/Makefile
- scripts/pack/ezxml/changelog.txt
- scripts/pack/ezxml/ezxml.c
- scripts/pack/ezxml/ezxml.h
- scripts/pack/ezxml/ezxml.html
- scripts/pack/ezxml/ezxml.txt
- scripts/pack/ezxml/license.txt
- scripts/pack/pack.c
modify the packaging scripts and add packaging support for SG2044 firmware
> Scripts: modify the packaging method of firmware.bin

- ramdisk/overlay/ap/etc/init.d/S60apveth
- ramdisk/overlay/rp/etc/init.d/S60rpveth
change ramdisk get ip from /proc/sgdrv/vethip
> change ramdisk get ip from /proc/sgdrv/vethip

- scripts/envsetup.sh
Add new command for generate cross-builder headers deb
> Add package cross-builder header debs command

- scripts/envsetup.sh
Only use CHIP=sg2044 to build image for chip.
> script: delete CHIP=bm1690 build script.

- scripts/gen_sg2044_img.sh
- Add kernel-devel RPM to the build process for development support.
- Refine kernel RPM installation pattern to target specific versions.
> scripts: gen_sg2044_img: include kernel-devel package

- scripts/gen_sg2042_img.sh
Fixed the error of mounting /run directory conflict when compiling euler image
> scripts:gen_sg2042_image:Fixed compilation error
